import './globals.css'
import { Inter } from 'next/font/google'
import Lazyloader from '@/components/Lazyloader'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alif Noon Properties',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Lazyloader>{children}</Lazyloader>
      </body>
    </html>
  )
}
